- hosts: all
  become: True
  roles:
    - role: common
  tasks:
    - name: Set docker squid options (systemd)
      template:
        src: templates/squid.service
        dest: /etc/systemd/system/squid.service
        owner: root
        group: root
        mode: 0644
      notify:
        - Reload systemd
        - Enable squid
        - Restart squid
      when: ansible_distribution_version|version_compare(15.04, '>=')
    - name: HTTP_PROXY for all users pointing to docker-squid
      copy: src=files/http-proxy.sh
            dest=/etc/profile.d
    - name: Apt using docker-squid
      copy: src=files/95proxy
            dest=/etc/apt/apt.conf.d/
