- hosts: all
  become: True
  roles:
    - role: angstwad.docker_ubuntu
      docker_opts: >
        --storage-driver btrfs
  vars:
    - realuser: "{{ lookup('env', 'USER') }}"
  tasks:
    - user: name={{ realuser }} groups=docker append=yes
    - debug: msg="{{ realuser }} added to docker group"
