- hosts: all
  connection: local
  sudo: True
  tasks:
    - name: Set docker squid options (systemd)
      template:
        src: templates/squid.service
        dest: /etc/systemd/system/squid.service
        owner: root
        group: root
        mode: 0644
      notify:
        - Reload systemd
        - Restart squid
      when: ansible_distribution_version|version_compare(15.04, '>=')
    - name: Force squid restart
      command: systemctl restart squid
