- hosts: all
  become: True
  tasks:
    - name: install development packages
      apt: pkg={{item}}
      with_items:
        - blueman
        - exfat-fuse
        - exfat-utils
        - git
        - gitk
        - gparted
        - htop
        - iotop
        - iptraf
        - mercurial
        - parted
        - screen
        - shutter
        - ssh
        - tcpdump
        - tmux
        - tree
        - vim
        - vim-common
        - volumeicon-alsa
        - wget
        - xclip
        - xbacklight
        - zsh
    - name: install i3 and related packages
      apt: pkg={{item}}
      with_items:
        - dmenu
        - dunst
        - i3
        - i3lock
        - i3status
    - name: install powerline
      apt: pkg={{item}}
      with_items:
        - powerline
        - python-demjson
