---
- name: Start Docker
  service: name=docker state=started

- name: Reload docker
  service: name=docker state=reloaded

- name: Reload systemd
  command: systemctl daemon-reload  

- name: Restart docker
  service: name=docker state=restarted

- name: Restart dockerio
  service: name=docker.io state=restarted

- name: Restart devpi
  service: name=devpi state=restarted

- name: Enable devpi
  service: name=devpi enabled=yes

- name: Restart squid
  service: name=squid state=restarted

- name: Enable squid
  service: name=squid enabled=yes

- name: Restart NetworkManager
  service: name=NetworkManager state=restarted
