---
general:
  - blueman
  - git
  - gitk
  - gparted
  - htop
  - iotop
  - iptraf
  - mercurial
  - parted
  - screen
  - shutter
  - ssh
  - tcpdump
  - tmux
  - tree
  - vim
  - vim-common
  - volumeicon-alsa
  - wget
  - xclip
  - xbacklight
  - zsh
  - golang

i3:
  - dmenu
  - dunst
  - i3
  - i3lock
  - i3status

powerline:
  - powerline
  - python-demjson
